### ISSUE TITLE
"'module' object has no attribute 'is_ip'" error

### ISSUE THREAD

**Issue by jw47** [clowwindy/ChinaDNS#83]
After install ChinaDNS on Mac, I got the error below:

sudo chinadns
2015-04-07 05:04:17 INFO     starting dns at 127.0.0.1:53
Traceback (most recent call last):
  File "/usr/local/bin/chinadns", line 9, in <module>
    load_entry_point('chinadns==0.2.3', 'console_scripts', 'chinadns')()
  File "/Library/Python/2.7/site-packages/chinadns/dnsrelay.py", line 404, in main
    udprelay = UDPDNSRelay(config)
  File "/Library/Python/2.7/site-packages/chinadns/dnsrelay.py", line 131, in __init__
    DNSRelay.__init__(self, config)
  File "/Library/Python/2.7/site-packages/chinadns/dnsrelay.py", line 76, in __init__
    self._parse_hosts()
  File "/Library/Python/2.7/site-packages/chinadns/dnsrelay.py", line 95, in _parse_hosts
    if asyncdns.is_ip(ip):
AttributeError: 'module' object has no attribute 'is_ip'

What's the problem? Thanks!

**Comment by clowwindy** [comment]
Please use this C version.
